// This file is auto-generated by a build script. Do not edit manually.

export const MIGRATION_HASHES = [
  "bb874395de89233f5cd7f3099d16e6cd31c6de29b317cbfe72c585f3095627e7",
  "133e7221bfd3d166878b10f894fdcefe98c20fcfa8459037e29f5a0950d5d056"
];
