// This file is auto-generated by `npm run db:generate-hashes`. Do not edit manually.

export const MIGRATION_HASHES: string[] = [
  "bb874395de89233f5cd7f3099d16e6cd31c6de29b317cbfe72c585f3095627e7",
  "e30ec61b45156e6d7a9c03cf6c32486cf0fe8e38d0a69223b479046121959b0b",
];
